version: '3.8'
services:
  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./tmp/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  api:
    build: ./api/
    command: bash -c "rm -f tmp/pids/server.pid && rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./api:/api
    ports:
      - "3001:3000"
    depends_on:
      - db

  front:
    build: ./front/
    volumes:
      - ./front:/front
    command: sh -c "npm start"
    ports:
      - "3000:3000"
