module ShopifyHelper
  def shopify_header
    [
      'Handle',
      'Title',
      'Body (HTML)',
      'Vendor',
      'Product Category',
      'Type',
      'Tags',
      'Published',
      'Option1 Name',
      'Option1 Value',
      'Option2 Name',
      'Option2 Value',
      'Option3 Name',
      'Option3 Value',
      'Variant SKU',
      'Variant Grams',
      'Variant Inventory Tracker',
      'Variant Inventory Qty',
      'Variant Inventory Policy',
      'Variant Fulfillment Service',
      'Variant Price',
      'Variant Compare At Price',
      'Variant Requires Shipping',
      'Variant Taxable	',
      'Variant Barcode',
      'Image Src',
      'Image Position',
      'Image Alt Text',
      'Gift Card',
      'SEO Title',
      'SEO Description',
      'Google Shopping / Google Product Category',
      'Google Shopping / Gender',
      'Google Shopping / Age Group',
      'Google Shopping / MPN	',
      'Google Shopping / AdWords Grouping',
      'Google Shopping / AdWords Labels',
      'Google Shopping / Condition',
      'Google Shopping / Custom Product',
      'Google Shopping / Custom Label 0',
      'Google Shopping / Custom Label 1',
      'Google Shopping / Custom Label 2',
      'Google Shopping / Custom Label 3',
      'Google Shopping / Custom Label 4',
      'Variant Image',
      'Variant Weight Unit',
      'Variant Tax Code',
      'Cost per item',
      'Price / Eurozone',
      'Compare At Price / Eurozone	',
      'Price / International',
      'Compare At Price / International',
      'Price / United Kingdom',
      'Compare At Price / United Kingdom',
      'Price / United States',
      'Compare At Price / United States',
      'Status',
    ]
  end
  def shopify_format(value)
    [
      'aaa', # 'Handle',
      'aaa', # 'Title',
      'aaa', # 'Body (HTML)',
      'aaa', # 'Vendor',
      'aaa', # 'Product Category',
      'aaa', # 'Type',
      'aaa', # 'Tags',
      'aaa', # 'Published',
      'aaa', # 'Option1 Name',
      'aaa', # 'Option1 Value',
      'aaa', # 'Option2 Name',
      'aaa', # 'Option2 Value',
      'aaa', # 'Option3 Name',
      'aaa', # 'Option3 Value',
      'aaa', # 'Variant SKU',
      'aaa', # 'Variant Grams',
      'aaa', # 'Variant Inventory Tracker',
      'aaa', # 'Variant Inventory Qty',
      'aaa', # 'Variant Inventory Policy',
      'aaa', # 'Variant Fulfillment Service',
      'aaa', # 'Variant Price',
      'aaa', # 'Variant Compare At Price',
      'aaa', # 'Variant Requires Shipping',
      'aaa', # 'Variant Taxable	',
      'aaa', # 'Variant Barcode',
      'aaa', # 'Image Src',
      'aaa', # 'Image Position',
      'aaa', # 'Image Alt Text',
      'aaa', # 'Gift Card',
      'aaa', # 'SEO Title',
      'aaa', # 'SEO Description',
      'aaa', # 'Google Shopping / Google Product Category',
      'aaa', # 'Google Shopping / Gender',
      'aaa', # 'Google Shopping / Age Group',
      'aaa', # 'Google Shopping / MPN	',
      'aaa', # 'Google Shopping / AdWords Grouping',
      'aaa', # 'Google Shopping / AdWords Labels',
      'aaa', # 'Google Shopping / Condition',
      'aaa', # 'Google Shopping / Custom Product',
      'aaa', # 'Google Shopping / Custom Label 0',
      'aaa', # 'Google Shopping / Custom Label 1',
      'aaa', # 'Google Shopping / Custom Label 2',
      'aaa', # 'Google Shopping / Custom Label 3',
      'aaa', # 'Google Shopping / Custom Label 4',
      'aaa', # 'Variant Image',
      'aaa', # 'Variant Weight Unit',
      'aaa', # 'Variant Tax Code',
      'aaa', # 'Cost per item',
      'aaa', # 'Price / Eurozone',
      'aaa', # 'Compare At Price / Eurozone	',
      'aaa', # 'Price / International',
      'aaa', # 'Compare At Price / International',
      'aaa', # 'Price / United Kingdom',
      'aaa', # 'Compare At Price / United Kingdom',
      'aaa', # 'Price / United States',
      'aaa', # 'Compare At Price / United States',
      'aaa', # 'Status',
    ]
  end
end